### ISSUE TITLE
Custom Query

### ISSUE THREAD

**Issue by rorc** [lichtner/fluentpdo#109]
FluentPDO destroys my custom query :(

...... ->where('EXISTS(SELECT 1 FROM table AS tbl WHERE id IN (1,2,3)')

**Comment by lichtner** [comment]
for subselect use direct pdo

**Comment by rorc** [comment]
Its very uncomfortably if i have many-many terms with queryBuilder before...

**Comment by lichtner** [comment]
so implement this feature and don't hesitate send pull request. You are very welcome.
