### ISSUE TITLE
Raw Query

### ISSUE THREAD

**Issue by iqbalmalik89** [lichtner/fluentpdo#122]
I want to get the raw query of a fluent based query.

My fluent query is this.

$query = $con->deleteFrom('jobs')->where('id', 1)->execute();

I need to show query like this.

DELETE from Jobs where id = 1

Is there any way to get query in raw format?

**Comment by gephaest** [comment]
Sure, just replace `execute()` to `getQuery(false)` (false means get query without formatting)

**Comment by lichtner** [comment]
@gephaest  thanks
