### ISSUE TITLE
Toggle A boolean in SET statement

### ISSUE THREAD

**Issue by 2b3ez** [lichtner/fluentpdo#133]
How Can I do to perform this query with FluentPDO ?

UPDATE table1 SET active = NOT active WHERE id=xxx;

Thx to community ;)

**Comment by maldoinc** [comment]
I think this should do it

```php
$fluent->update('table1', ['active' => new FluentLiteral('not active')], $id);
```

**Comment by 2b3ez** [comment]
That's it !

Thanks!
