### ISSUE TITLE
Bug in 'where' clause when It's present a postgresql cast operator

### ISSUE THREAD

**Issue by tomasdelvechio** [lichtner/fluentpdo#136]
Hi, sorry if this error isn't from FluentPDO.

I want to build the next query

```
SELECT person.* FROM person WHERE name::varchar = ? ORDER BY name
```

and I use FluentPDO like here:

```
$fpdo->from('person')
         ->where('name::varchar','Somename')
         ->orderBy('name')->fetchAll();
```

But the query building for the FluentPDO is:

```
SELECT person.* FROM person LEFT JOIN name ON name.person_id = person.id WHERE name::varchar = ? ORDER BY name
```

Observe the LEFT JOIN with the name column like a table.

I think the expected behavior should be the first query.

**Comment by jkufner** [comment]
This is because FluentPDO's smart join feature. It is really annoying
feature :)

See
https://github.com/lichtner/fluentpdo/commit/29ce9aaa4a0794180235adf50e587129f99a9a0c

**Comment by tomasdelvechio** [comment]
Ok, thanks
