### ISSUE TITLE
Composer Stability

### ISSUE THREAD

**Issue by dgee2** [lichtner/fluentpdo#87]
Is there any chance of creating a stable build tag (I'm guessing 0.0.1 or similar) so that the composer package can be loaded in to other composer packages with greater ease?

**Comment by Rotmistrz** [comment]
Thus, is the stable version done? I can't make use of my repository, which works with FluentPDO, in the other project. Composer wants to get the stable version, when it isn't the root project.

**Comment by dgee2** [comment]
@lichtner is there any movement on this? If there isn't in the near future I'll have to look into either creating a separate forked version or leaving the library completely as I'm not able to use packageso that haven't been marked stable explicitly.

**Comment by magnus-eriksson** [comment]
C'mon. It's soooo easy to tag a release.
```
git tag 1.0.0 (or whatever)
git push origin 1.0.0
```
Done! And after that other developers can use this package as a dependecy without any problems.

**Comment by lichtner** [comment]
Ok guys, 1.0.0 was released right now!!! :beers:

**Comment by magnus-eriksson** [comment]
:joy_cat: Awesome. Thanks! :smiley:
